defaults:
  - _self_
  - data: cifar10
  - model: cifar

model:
  # model Params
  arch: resnet50
  first_conv: True
  maxpool1: True
  hidden_mlp: 2048
  feat_dim: 128
  online_ft: True

  # transform params
  gaussian_blur: False
  jitter_strength: 1.0
  warmup_epochs: 10
  batch_size: 128 # batch size per gpu

  optimizer: adam # [adam, lars]
  exclude_bn_bias: True
  learning_rate: 1e-3
  weight_decay: 1e-6
  start_lr: 0
  final_lr: 1e-6

  temperature: 0.1


base:
  data_root: ${oc.env:DATA_ROOT} # Path to Data

trainer:
  seed: 12345
  fast_dev_run: False
  experiments_root: ${oc.env:EXPERIMENT_ROOT}/SSL/${data.dataset}
  experiment_name: test
  experiment_id: ${now:%Y-%m-%d_%H-%M-%S-%f}
  gpus: 1
  num_nodes: 1 # number of nodes used for training
  num_workers: 8 # num workers used per GPU

  max_epochs: 100 # number of epochs to train
  max_steps: -1 

  check_val_every_n_epoch: 1
  progress_bar_refresh_rate: 10
  gradient_clip_val: 0
  early_stop: False
  precision: 16
  deterministic: False

hydra:
  run:
    dir: ${trainer.experiments_root}/${trainer.experiment_name}/${trainer.experiment_id}