
arch: resnet18
first_conv: False
maxpool1: False
hidden_mlp: 512
feat_dim: 128
weight_decay: 1e-4
learning_rate: 1
optimizer: lars

gaussian_blur: False
jitter_strength: 0.5

temperature: 0.5

batch_size: 512
