arch: resnet18
first_conv: True
maxpool1: True
hidden_mlp: 512
feat_dim: 128
# weight_decay: 1e-4
# learning_rate: 1
optimizer: lars

gaussian_blur: True
jitter_strength: 1.0
learning_rate: 4.8 
final_lr: 0.0048 
start_lr: 0.3 

temperature: 0.1

batch_size: 256
