defaults:
  - trainer: base
  - _self_
  - data: toy_moons
  - optim: adam
  - model: bayesian_mlp
  # - hydra/job_logging: colorlog
  # - hydra/hydra_logging: colorlog
  - active: toy_two_moons
  - query: entropy

trainer:
  batch_size: 64
  num_workers: 16
  persistent_workers: False
  max_epochs: 40
  min_epochs: 0
  experiment_name: 2d_toy_test
  vis_callback: False # this enables or disables visualizations of training

hydra:
  run:
    dir: ${trainer.experiments_root}/${trainer.experiment_name}/${trainer.experiment_id}

# test:
#   checkpoint_path:

