defaults:
  - data: cifar10
  - optim: sgd_fixmatch
  # - model: wideresnet-cifar10
  - model: resnet_fixmatch
  # - hydra/job_logging: colorlog
  # - hydra/hydra_logging: colorlog
  - sem_sl : fixmatch
  - query: entropy
  - active: standard

trainer:
  seed: 12345
  batch_size: 64
  # batch_size: 128
  # n_steps: 400
  max_epochs: 200
  min_epochs: 50
  fast_dev_run: False
  data_root: ${oc.env:DATA_ROOT}
  experiments_root: ${oc.env:EXPERIMENT_ROOT}/activelearning
  experiment_name: test_fixmatch
  experiment_id: ${now:%Y-%m-%d_%H-%M-%S-%f}
  n_gpus: 1
  check_val_every_n_epoch: 1
  progress_bar_refresh_rate: 10
  gradient_clip_val: 0
  early_stop: False
  precision: 16
  deterministic: False
  profiler: simple

hydra:
  run:
    dir: ${trainer.experiments_root}/${trainer.experiment_name}/${trainer.experiment_id}

# test:
#   checkpoint_path: