name: bayesian_wide_resnet
model_width: 2
model_depth: 28
weight_decay: 0.0005
learning_rate: 0.03
dropout_p: 0
load_pretrained: Null
freeze_encoder: False
use_ema: False
exclude_bn_bias: True
k: 50
finetune: False
small_head: True